### ISSUE TITLE
PR training for everyone!

### ISSUE THREAD

**Issue by vtiinanen** [CumbersomePack/SmartCanvas#4]
Lets kick things off by training Pull Request making. :foot: 

First of all. :1st_place_medal: 

Clone the repository.

`git clone https://github.com/CumbersomePack/SmartCanvas.git`

`cd SmartCanvas`

You are at the main branch when you freshly clone a repository.

Good, you want to develop features only according to our issues or other PRs. We want to keep the traceability through out the development process. For that reason we name our development branches this way.

Make yourself a branch.

`git checkout -b ISSUE-N-INITIALS`

Good. Now you have your own branch to tinker with.

Add yourself to the contributors list in the README.md

`git add README.md`

`git commit -m "ISSUE-N: Add <name> to contributors"`

`git push origin  ISSUE-N-INITIALS`

**My example would be:**

`git checkout -b ISSUE-4-VT`
Add myself to the contributors list in the README.md
`git add README.md`
`git commit -m "ISSUE-4: Add Vili to contributors"`
`git push origin  ISSUE-4-VT`

This change relates to issue #4 and the initials will tell who did it.

Good, now your branch should be in the GitHub remote. You can start the Pull Request process from the GitHub UI.

![image](https://user-images.githubusercontent.com/49340148/133279613-76fc6b02-7a2b-4a6c-87f8-bcb0059a82f1.png)

Now you need a review from 2 other developers to get the chance to merge your branch to the main branch.

Our Discord automatically gets notified about new PR's. 

If no one reviews your PR in timely manner, then start shouting in Discord channel 😄 

Now if everything is okay you can merge the change and remove the branch.

Then you can start on the next issue :wink:

**Comment by vtiinanen** [comment]
Should others do also the test PR?

**Comment by vtiinanen** [comment]
Please, those that have not yet done this. Do it.

**Comment by hengzhang-pro** [comment]
Since this is a University course-driven open source project, the participation period of each team is only for a few months of the course, I would like to suggest that at the beginning of each team take over, 1-2 contributors can be nominated to be responsible for repository management and code quality, it can be voluntary or elective by team. It aims to make the code quality of the repository and the project development cooperation smoother. At the same time, it can also cultivate the collaborative working ability of the participants.
